[2023-11-29T14:27:05.541+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: football-etl.load_to_sql scheduled__2023-02-17T00:00:00+00:00 [queued]>
[2023-11-29T14:27:05.555+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: football-etl.load_to_sql scheduled__2023-02-17T00:00:00+00:00 [queued]>
[2023-11-29T14:27:05.556+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-11-29T14:27:05.557+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2023-11-29T14:27:05.557+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-11-29T14:27:05.578+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): load_to_sql> on 2023-02-17 00:00:00+00:00
[2023-11-29T14:27:05.589+0000] {standard_task_runner.py:55} INFO - Started process 308 to run task
[2023-11-29T14:27:05.592+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'football-etl', 'load_to_sql', 'scheduled__2023-02-17T00:00:00+00:00', '--job-id', '339', '--raw', '--subdir', 'DAGS_FOLDER/dag-football.py', '--cfg-path', '/tmp/tmpewxwhntg']
[2023-11-29T14:27:05.593+0000] {standard_task_runner.py:83} INFO - Job 339: Subtask load_to_sql
[2023-11-29T14:27:05.670+0000] {task_command.py:388} INFO - Running <TaskInstance: football-etl.load_to_sql scheduled__2023-02-17T00:00:00+00:00 [running]> on host 6377c365460c
[2023-11-29T14:27:05.751+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=football-etl
AIRFLOW_CTX_TASK_ID=load_to_sql
AIRFLOW_CTX_EXECUTION_DATE=2023-02-17T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-02-17T00:00:00+00:00
[2023-11-29T14:27:05.755+0000] {load_to_sql.py:16} INFO - Reading the joined tables...
[2023-11-29T14:27:05.772+0000] {load_to_sql.py:23} INFO - Loading joined tables to PostgreSQL...
[2023-11-29T14:27:13.388+0000] {load_to_sql.py:46} ERROR - SQLAlchemyError occurred while connecting to the database: (psycopg2.errors.UndefinedTable) table "matches" does not exist

[SQL: 
DROP TABLE matches]
(Background on this error at: https://sqlalche.me/e/14/f405)
[2023-11-29T14:27:13.389+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-11-29T14:27:13.398+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=football-etl, task_id=load_to_sql, execution_date=20230217T000000, start_date=20231129T142705, end_date=20231129T142713
[2023-11-29T14:27:13.515+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2023-11-29T14:27:13.534+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
