[2023-11-29T13:58:50.650+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: football-etl.extract_matches scheduled__2023-02-09T00:00:00+00:00 [queued]>
[2023-11-29T13:58:50.663+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: football-etl.extract_matches scheduled__2023-02-09T00:00:00+00:00 [queued]>
[2023-11-29T13:58:50.664+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-11-29T13:58:50.665+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2023-11-29T13:58:50.665+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-11-29T13:58:50.690+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): extract_matches> on 2023-02-09 00:00:00+00:00
[2023-11-29T13:58:50.699+0000] {standard_task_runner.py:55} INFO - Started process 2096 to run task
[2023-11-29T13:58:50.703+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'football-etl', 'extract_matches', 'scheduled__2023-02-09T00:00:00+00:00', '--job-id', '200', '--raw', '--subdir', 'DAGS_FOLDER/dag-football.py', '--cfg-path', '/tmp/tmpujndwtil']
[2023-11-29T13:58:50.704+0000] {standard_task_runner.py:83} INFO - Job 200: Subtask extract_matches
[2023-11-29T13:58:51.009+0000] {task_command.py:388} INFO - Running <TaskInstance: football-etl.extract_matches scheduled__2023-02-09T00:00:00+00:00 [running]> on host 6377c365460c
[2023-11-29T13:58:51.150+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=football-etl
AIRFLOW_CTX_TASK_ID=extract_matches
AIRFLOW_CTX_EXECUTION_DATE=2023-02-09T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-02-09T00:00:00+00:00
[2023-11-29T13:58:52.689+0000] {extract_matches.py:60} INFO - Data exported to files/match_data.csv successfully.
[2023-11-29T13:58:52.692+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/script/extract_matches.py", line 97, in extract_matches
    print(pd.read_csv(csv_filename))
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 69, in __init__
    self._reader = parsers.TextReader(self.handles.handle, **kwds)
  File "pandas/_libs/parsers.pyx", line 549, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
[2023-11-29T13:58:52.713+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=football-etl, task_id=extract_matches, execution_date=20230209T000000, start_date=20231129T135850, end_date=20231129T135852
[2023-11-29T13:58:52.733+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 200 for task extract_matches (No columns to parse from file; 2096)
[2023-11-29T13:58:52.761+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-11-29T13:58:53.125+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
