[2023-11-29T14:28:27.578+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: football-etl.load_to_sql scheduled__2023-03-09T00:00:00+00:00 [queued]>
[2023-11-29T14:28:27.589+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: football-etl.load_to_sql scheduled__2023-03-09T00:00:00+00:00 [queued]>
[2023-11-29T14:28:27.589+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-11-29T14:28:27.590+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2023-11-29T14:28:27.590+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-11-29T14:28:27.791+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): load_to_sql> on 2023-03-09 00:00:00+00:00
[2023-11-29T14:28:27.817+0000] {standard_task_runner.py:55} INFO - Started process 721 to run task
[2023-11-29T14:28:27.820+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'football-etl', 'load_to_sql', 'scheduled__2023-03-09T00:00:00+00:00', '--job-id', '426', '--raw', '--subdir', 'DAGS_FOLDER/dag-football.py', '--cfg-path', '/tmp/tmpeepkrje9']
[2023-11-29T14:28:27.821+0000] {standard_task_runner.py:83} INFO - Job 426: Subtask load_to_sql
[2023-11-29T14:28:27.890+0000] {task_command.py:388} INFO - Running <TaskInstance: football-etl.load_to_sql scheduled__2023-03-09T00:00:00+00:00 [running]> on host 6377c365460c
[2023-11-29T14:28:27.972+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=football-etl
AIRFLOW_CTX_TASK_ID=load_to_sql
AIRFLOW_CTX_EXECUTION_DATE=2023-03-09T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-09T00:00:00+00:00
[2023-11-29T14:28:27.975+0000] {load_to_sql.py:16} INFO - Reading the joined tables...
[2023-11-29T14:28:27.994+0000] {load_to_sql.py:23} INFO - Loading joined tables to PostgreSQL...
[2023-11-29T14:28:29.276+0000] {load_to_sql.py:46} ERROR - SQLAlchemyError occurred while connecting to the database: (psycopg2.OperationalError) connection to server at "lucky.db.elephantsql.com" (54.195.214.215), port 5432 failed: FATAL:  too many connections for role "xckamlge"

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-11-29T14:28:29.276+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-11-29T14:28:29.288+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=football-etl, task_id=load_to_sql, execution_date=20230309T000000, start_date=20231129T142827, end_date=20231129T142829
[2023-11-29T14:28:29.316+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2023-11-29T14:28:29.335+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
