[2023-11-29T14:27:36.403+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: football-etl.load_to_sql scheduled__2023-03-05T00:00:00+00:00 [queued]>
[2023-11-29T14:27:36.420+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: football-etl.load_to_sql scheduled__2023-03-05T00:00:00+00:00 [queued]>
[2023-11-29T14:27:36.421+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-11-29T14:27:36.421+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2023-11-29T14:27:36.422+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-11-29T14:27:36.644+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): load_to_sql> on 2023-03-05 00:00:00+00:00
[2023-11-29T14:27:36.654+0000] {standard_task_runner.py:55} INFO - Started process 472 to run task
[2023-11-29T14:27:36.656+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'football-etl', 'load_to_sql', 'scheduled__2023-03-05T00:00:00+00:00', '--job-id', '375', '--raw', '--subdir', 'DAGS_FOLDER/dag-football.py', '--cfg-path', '/tmp/tmpf6taldj9']
[2023-11-29T14:27:36.657+0000] {standard_task_runner.py:83} INFO - Job 375: Subtask load_to_sql
[2023-11-29T14:27:36.747+0000] {task_command.py:388} INFO - Running <TaskInstance: football-etl.load_to_sql scheduled__2023-03-05T00:00:00+00:00 [running]> on host 6377c365460c
[2023-11-29T14:27:36.845+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=football-etl
AIRFLOW_CTX_TASK_ID=load_to_sql
AIRFLOW_CTX_EXECUTION_DATE=2023-03-05T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-05T00:00:00+00:00
[2023-11-29T14:27:36.848+0000] {load_to_sql.py:16} INFO - Reading the joined tables...
[2023-11-29T14:27:36.867+0000] {load_to_sql.py:23} INFO - Loading joined tables to PostgreSQL...
[2023-11-29T14:27:38.241+0000] {load_to_sql.py:46} ERROR - SQLAlchemyError occurred while connecting to the database: (psycopg2.OperationalError) connection to server at "lucky.db.elephantsql.com" (54.195.214.215), port 5432 failed: FATAL:  too many connections for role "xckamlge"

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-11-29T14:27:38.241+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-11-29T14:27:38.258+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=football-etl, task_id=load_to_sql, execution_date=20230305T000000, start_date=20231129T142736, end_date=20231129T142738
[2023-11-29T14:27:38.313+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2023-11-29T14:27:38.344+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
